export const en = {
  //firm info
  firm: {
    name: "CA Sandeep Sao & Associates",
    address:
      "13/1, Temple Road, 10thcrs, Malleswaram, Bangalore, Karnataka, 560003",
    mobile: "+91 02226 14670",
  },

  alreadyAnAccount: "Already have an account?",
  noAvailableOptions: "No Available options",
  noData: "Nothing to show!",
  searchTable: "Search Table",
  searchTaskName: "Search By Task Name",
  status: "Status",
  selectDateRange: "Select Date Range",
  addFilters: "Add Filters",

  myFirm: "My Firm",
  settings: "Settings",
  logout: "Logout",
  tasks: "Tasks",
  clients: "Clients",
  transactions: "Transactions",
  delete: "Delete",

  dashboard: "Dashboard",
  viewAll: "View All",
  allTasks: "All Tasks",
  createTask: "Create Task",
  createNewTask: "Create New Task",
  myTasks: "My Tasks",
  pending: "Pending",
  inProgress: "In Progress",
  completed: "Completed",
  overdue: "Overdue",
  approved: "Approved",
  creator: "Creator",
  startDate: "Start Date",
  taskName: "Task Name",
  client: "Client",
  newClient: "New Client",
  createNewClient: "Create New Client",
  assignee: "Assignee",
  creatorEmail: "Creator Email",
  endDate: "End Date",
  taskType: "Task Type",
  entity: "Entity",
  comments: "Comments",
  totalAmount: "Total Amount",
  paidAmount: "Paid Amount",
  balanceAmount: "Balance Amount",

  // login and signUp
  login: "Login",
  newHere: "New joinee?",
  signUp: "Sign-Up",
  fName: "First Name",
  lName: "Last Name",
  email: "Email",
  password: "Password",
  cnfPassword: "Confirm Password",
  heading: "CA",
  forgotPwd: "Forgot Password?",

  // Client Create Page
  name: "Name",
  gstIn: "GSTIN",
  registrationDate: "Date of Registration",
  taxpayerType: "Taxpayer Type",
  legalName: "Legal Name",
  businessName: "Name of Business",
  businessConstitution: "Constitution of Business",
  businessActivity: "Business Activity",
  entities: "Entities",
  panNumber: "PAN Number",
  address: "Address",
  city: "City",
  district: "District",
  state: "State",
  pincode: "PIN Code",
  primaryMobile: "Primary Mobile",
  secondaryMobile: "Secondary Mobile",
  primaryEmail: "Primary Email",
  gstUsername: "Username",
  gstPassword: "Password",
  contactDetails: "Contact Details",
  gstCreds: "GST Website Credentials",

  // toast messages
  toast: {
    custom404Error: "Invalid URL. Redirecting to dashboard.",
    successLogout: "User logged out successfully.",
    authFailed: "Authentication failed. Please re-login.",
    tasksFetchedSuccess: "Fetched all tasks successfully.",
    tasksFetchedFailed: "Failed to fetch all tasks.",
    myTasksFetchedSuccess: "Fetched user tasks successfully.",
    myTasksFetchedFailed: "Failed to fetch user tasks.",
    taskCreatedSuccess: "Created task successfully.",
    taskCreatedFailed: "Failed to create task.",
    taskUpdatedSuccess: "Updated task successfully.",
    taskUpdatedFailed: "Failed to update task.",
    taskDeletedSuccess: "Deleted task successfully.",
    taskDeletedFailed: "Failed to delete task.",
    taskTypeFetchSuccess: "Fetched task types successfully.",
    taskTypeFetchFailed: "Failed to fetch task types.",
    clientsFetchSuccess: "Fetched clients info successfully.",
    clientsFetchFailed: "Failed to fetch clients info.",
    taxpayerTypesFetchFailed: "Failed to fetch taxpayer types.",
    pincodesFetchFailed: "Failed to fetch pincodes.",
    clientCreatedSuccessfully: "Client information saved successfully.",
    clientCreatedFailed: "Failed to save client information.",
  },
};
