export const en = {
  //firm info
  firm: {
    name: "CA Sandeep Sao & Associates",
    address:
      "13/1, Temple Road, 10thcrs, Malleswaram, Bangalore, Karnataka, 560003",
    mobile: "+91 02226 14670",
  },

  noAvailableOptions: "No Available options",
  noData: "Nothing to show!",
  searchTable: "Search Table",
  searchTaskName: "Search By Task Name",
  status: "Status",
  selectDateRange: "Select Date Range",
  addFilters: "Add Filters",

  myFirm: "My Firm",
  settings: "Settings",
  logout: "Logout",
  tasks: "Tasks",
  clients: "Clients",
  transactions: "Transactions",
  delete: "Delete",

  dashboard: "Dashboard",
  viewAll: "View All",
  allTasks: "All Tasks",
  createTask: "Create Task",
  createNewTask: "Create New Task",
  myTasks: "My Tasks",
  pending: "Pending",
  inProgress: "In Progress",
  completed: "Completed",
  overdue: "Overdue",
  approved: "Approved",
  creator: "Creator",
  startDate: "Start Date",
  taskName: "Task Name",
  client: "Client",
  assignee: "Assignee",
  creatorEmail: "Creator Email",
  endDate: "End Date",
  taskType: "Task Type",
  entity: "Entity",
  comments: "Comments",

  // login and signUp
  login: "Login",
  newHere: "New joinee?",
  signUp: "Sign-Up",
  fName: "First Name",
  lName: "Last Name",
  email: "Email",
  password: "Password",
  cnfPassword: "Confirm Password",
  heading: "CA",
  forgotPwd: "Forgot Password?",

  // toast messages
  toast: {
    custom404Error: "Invalid URL. Redirecting to dashboard.",
    successLogout: "User logged out successfully.",
    authFailed: "Authentication failed. Please re-login.",
    tasksFetchedSuccess: "Fetched all tasks successfully.",
    tasksFetchedFailed: "Failed to fetch all tasks.",
    myTasksFetchedSuccess: "Fetched user tasks successfully.",
    myTasksFetchedFailed: "Failed to fetch user tasks.",
    taskUpdatedSuccess: "Updated task successfully.",
    taskUpdatedFailed: "Failed to update task.",
    taskDeletedSuccess: "Deleted task successfully.",
    taskDeletedFailed: "Failed to delete task.",
    taskTypeFetchSuccess: "Fetched task types successfully.",
    taskTypeFetchFailed: "Failed to fetch task types.",
    clientsFetchSuccess: "Fetched clients info successfully.",
    clientsFetchFailed: "Failed to fetch clients info.",
  },
};
