export const en = {
  //firm info
  firm: {
    name: "CA Sandeep Sao & Associates",
    address:
      "13/1, Temple Road, 10thcrs, Malleswaram, Bangalore, Karnataka, 560003",
    mobile: "+91 02226 14670",
  },

  wowSoEmpty: "Wow! So Empty.",

  alreadyAnAccount: "Already have an account?",
  noAvailableOptions: "No Available options",
  noData: "Nothing to show!",
  searchTable: "Search Table",
  searchTaskName: "Search By Task Name",
  status: "Status",
  selectDateRange: "Select Date Range",
  addFilters: "Add Filters",

  myFirm: "My Firm",
  settings: "Settings",
  logout: "Logout",
  tasks: "Tasks",
  clients: "Clients",
  transactions: "Transactions",
  delete: "Delete",

  dashboard: "Dashboard",
  viewAll: "View All",
  allTasks: "All Tasks",
  createTask: "Create Task",
  createNewTask: "Create New Task",
  createNewTaskType: "Create New Task Type",
  parentTaskType: "Parent Task Type",
  childTaskType: "Child Task Type",
  addTaskType: "Add Task Subtype",
  myTasks: "My Tasks",
  taskTypes: "Task Types",
  pending: "Pending",
  inProgress: "In Progress",
  completed: "Completed",
  overdue: "Overdue",
  approved: "Approved",
  creator: "Creator",
  startDate: "Start Date",
  taskName: "Task Name",
  client: "Client",
  personalInfo: "Personal Info",
  newClient: "New Client",
  createNewClient: "Create New Client",
  assignee: "Assignee",
  creatorEmail: "Creator Email",
  endDate: "End Date",
  taskType: "Task Type",
  taskSubtype: "Task Subtype",
  entity: "Entity",
  comments: "Comments",
  totalAmount: "Total Amount",
  paidAmount: "Paid Amount",
  balanceAmount: "Balance Amount",
  sendMessage: "Send Message",
  messageHistory: "Message History",
  updatedClientInfo: "Update Client Info",

  // login and signUp
  login: "Login",
  newHere: "New joinee?",
  signUp: "Sign-Up",
  fName: "First Name",
  lName: "Last Name",
  email: "Email",
  password: "Password",
  cnfPassword: "Confirm Password",
  heading: "CA",
  forgotPwd: "Forgot Password?",

  // Client Create Page
  code: "Code",
  prefix: "Prefix",
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  spouseName: "Spouse Fullname",
  fatherName: "Father's Fullname",
  dob: "Date of Birth",
  sex: "Sex",
  maritalStatus: "Marital Status",

  addressLine1: "Address Line 1",
  addressLine2: "Address Line 2",

  aadharNumber: "Aadhar Card Number",
  aadharName: "Name as per addhar",
  passportNumber: "Passport Number",

  name: "Name",
  gstIn: "GSTIN",
  registrationDate: "Date of Registration",
  taxpayerType: "Taxpayer Type",
  legalName: "Legal Name",
  businessName: "Name of Business",
  businessConstitution: "Constitution of Business",
  businessActivity: "Business Activity",
  entities: "Entities",
  panNumber: "PAN Number",
  address: "Address",
  city: "City",
  district: "District",
  state: "State",
  pincode: "PIN Code",
  primaryMobile: "Primary Mobile",
  secondaryMobile: "Secondary Mobile",
  primaryEmail: "Primary Email",
  gstUsername: "Username",
  gstPassword: "Password",
  contactDetails: "Contact Details",
  gstCreds: "GST Website Credentials",
  businessDetails: "Business Details",
  bankDetails: "Bank Details",
  bankIFSC: "IFSC",
  bankMICR: "MICR",
  bankName: "Name",
  bankBranch: "Branch",
  bankAddress: "Address",
  bankCity: "City",
  bankState: "State",
  bankCentre: "Centre",
  bankContact: "Contact",

  // Message
  selectContacts: "Select Contacts",
  selectedContacts: "Selected Contacts",
  message: "Message",
  searchByNameNumber: "Search by name or mobile",
  templates: "Templates",

  // Notifications Message
  NEW: "A new task is assigned to you.",
  UPDATE: "There's an update on your task",

  // toast messages
  toast: {
    custom404Error: "Invalid URL. Redirecting to dashboard.",
    successLogout: "User logged out successfully.",
    authFailed: "Authentication failed. Please re-login.",
    tasksFetchedSuccess: "Fetched all tasks successfully.",
    tasksFetchedFailed: "Failed to fetch all tasks.",
    myTasksFetchedSuccess: "Fetched user tasks successfully.",
    myTasksFetchedFailed: "Failed to fetch user tasks.",
    taskCreatedSuccess: "Created task successfully.",
    taskCreatedFailed: "Failed to create task.",
    taskUpdatedSuccess: "Updated task successfully.",
    taskUpdatedFailed: "Failed to update task.",
    taskDeletedSuccess: "Deleted task successfully.",
    taskDeletedFailed: "Failed to delete task.",
    taskTypeFetchSuccess: "Fetched task types successfully.",
    taskTypeFetchFailed: "Failed to fetch task types.",
    taskTypeAddSuccess: "Added task types successfully.",
    taskTypeAddFailed: "Failed to add task types.",
    clientsFetchSuccess: "Fetched clients info successfully.",
    clientsFetchFailed: "Failed to fetch clients info.",
    clientTasksFetchSuccess: "Fetched clients' tasks successfully.",
    clientTasksFetchFailed: "Failed to fetch clients' tasks.",
    taxpayerTypesFetchFailed: "Failed to fetch taxpayer types.",
    pincodesFetchFailed: "Failed to fetch pincodes.",
    clientCreatedSuccessfully: "Client information saved successfully.",
    clientCreatedFailed: "Failed to save client information.",
    clientUpdatedSuccessfully: "Client information updated successfully.",
    clientUpdatedFailed: "Failed to update client information.",
  },
};
