export const QUERY_KEYS = {
  GET_CUSTOMERS: "GET_CUSTOMERS",
  GET_CUSTOMER_DETAILS: "GET_CUSTOMER_DETAILS",
  POST_CUSTOMER: "POST_CUSTOMER",
  PATCH_CUSTOMER: "PATCH_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",
};
